spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sfg_dev
    username: sfg_dev_user
    password: 123456
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true