spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sfg_prod
    username: sfg_prod_user
    password: 123456
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    database: mysql
    show-sql: false